[Ic2a]
Meter=Shape
MeterStyle=BRG|PG3|CSTI
Y=105
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Settings\ColorSpectrum" "Config.ini"]

[Colo2]
Meter=String
MeterStyle=Style|STTitre|PG3
Text=#T2P9#2: 
Y=100

[CurC2]
Meter=Image
MeterStyle=CT
SolidColor=#DA1#
X=50r
Y=4r

[CColo2]
Meter=String
MeterStyle=Style|PG3
Text=(#OACT#) 
X=35r
Y=102

[D225]
Meter=Image
MeterStyle=C225|STPC
LeftMouseUpAction=[#VVS# "DA1" "255,255,0" #@#Style.inc]#MTAJR1##Cout2#
X=180
Y=130

[D325]
Meter=Image
MeterStyle=C325|STPC
LeftMouseUpAction=[#VVS# "DA1" "255,153,0,255" #@#Style.inc]#MTAJR1##Cout3#

[D425]
Meter=Image
MeterStyle=C425|STPC
LeftMouseUpAction=[#VVS# "DA1" "255,27,10" #@#Style.inc]#MTAJR1##Cout4#

[D525]
Meter=Image
MeterStyle=C525|STPC
LeftMouseUpAction=[#VVS# "DA1" "255,0,255" #@#Style.inc]#MTAJR1##Cout5#

[D623]
Meter=Image
MeterStyle=C623|STPC
LeftMouseUpAction=[#VVS# "DA1" "236,0,140" #@#Style.inc]#MTAJR1##Cout6#

[D720]
Meter=Image
MeterStyle=C720|STPC
LeftMouseUpAction=[#VVS# "DA1" "201,255,92, 255" #@#Style.inc]#MTAJR1##Cout7#

[D818]
Meter=Image
MeterStyle=C818|STPC
LeftMouseUpAction=[#VVS# "DA1" "187,187,176,255" #@#Style.inc]#MTAJR1##Cout8#

[D916]
Meter=Image
MeterStyle=C916|STPC
LeftMouseUpAction=[#VVS# "DA1" "161,0,253" #@#Style.inc]#MTAJR1##Cout9#

[D1014]
Meter=Image
MeterStyle=C1014|STPC
LeftMouseUpAction=[#VVS# "DA1" "140,220,57" #@#Style.inc]#MTAJR1##Cout10#

[T201]
Meter=Image
MeterStyle=T101|STPC
LeftMouseUpAction=[#VVS# "DA1" "161,0,79" #@#Style.inc]#MTAJR1##Cout11#

[D111]
Meter=Image
MeterStyle=C111|STPC
LeftMouseUpAction=[#VVS# "DA1" "134,108,155" #@#Style.inc]#MTAJR1##Cout12#

[D211]
Meter=Image
MeterStyle=T111|STPC
LeftMouseUpAction=[#VVS# "DA1" "252,252,252" #@#Style.inc]#MTAJR1##Cout13#

[D121]
Meter=Image
MeterStyle=C121|STPC
LeftMouseUpAction=[#VVS# "DA1" "130, 227, 113, 89" #@#Style.inc]#MTAJR1##Cout14#

[D131]
Meter=Image
MeterStyle=C131|STPC
LeftMouseUpAction=[#VVS# "DA1" "128,128,64" #@#Style.inc]#MTAJR1##Cout15#

[d141]
Meter=Image
MeterStyle=C141|STPC
LeftMouseUpAction=[#VVS# "DA1" "128,64,0,255" #@#Style.inc]#MTAJR1##Cout16#

[D159]
Meter=Image
MeterStyle=C159|STPC
LeftMouseUpAction=[#VVS# "DA1" "98,46,105" #@#Style.inc]#MTAJR1##Cout17#

[D166]
Meter=Image
MeterStyle=C166|STPC
LeftMouseUpAction=[#VVS# "DA1" "64,128,128" #@#Style.inc]#MTAJR1##Cout18#

[D176]
Meter=Image
MeterStyle=C176|STPC
LeftMouseUpAction=[#VVS# "DA1" "64,0,128" #@#Style.inc]#MTAJR1##Cout19#

[D184]
Meter=Image
MeterStyle=C184|STPC
LeftMouseUpAction=[#VVS# "DA1" "64,153,224" #@#Style.inc]#MTAJR1##Cout20#

[D1901]
Meter=Image
MeterStyle=C1901|STPC
LeftMouseUpAction=[#VVS# "DA1" "0, 171, 255, 255" #@#Style.inc]#MTAJR1##Cout21#

[D2001]
Meter=Image
MeterStyle=C2001|STPC
LeftMouseUpAction=[#VVS# "DA1" "0,128,192" #@#Style.inc]#MTAJR1##Cout22#

[D2101]
Meter=Image
MeterStyle=C2101|STPC
LeftMouseUpAction=[#VVS# "DA1" "0,128,0" #@#Style.inc]#MTAJR1##Cout23#

[D2200]
Meter=Image
MeterStyle=C2200|STPC
LeftMouseUpAction=[#VVS# "DA1" "0,0,255" #@#Style.inc]#MTAJR1##Cout24#

[C1230]
Meter=Image
MeterStyle=C230|STPC
LeftMouseUpAction=[#VVS# "DA1" "0,0,0" #@#Style.inc]#MTAJR1##Cout25#

[T1230]
Meter=Image
MeterStyle=T230|STPC
LeftMouseUpAction=[#VVS# "DA1" "60,60,60" #@#Style.inc]#MTAJR1##Cout26#

[T1121]
Meter=Image
MeterStyle=T121|STPC
LeftMouseUpAction=[#VVS# "DA1" "225,225,225" #@#Style.inc]#MTAJR1##Cout27#

[V1230]
Meter=Image
MeterStyle=V230|STPC
LeftMouseUpAction=[#VVS# "DA1" "102,131,144" #@#Style.inc]#MTAJR1##Cout28#

[V1240]
Meter=Image
MeterStyle=V240|STPC
LeftMouseUpAction=[#VVS# "DA1" "208,52,56" #@#Style.inc]#MTAJR1##Cout29#

[V1250]
Meter=Image
MeterStyle=V250|STPC
LeftMouseUpAction=[#VVS# "DA1" "253,108,63" #@#Style.inc]#MTAJR1##Cout30#

[V1260]
Meter=Image
MeterStyle=V260|STPC
LeftMouseUpAction=[#VVS# "DA1" "249,78,124" #@#Style.inc]#MTAJR1##Cout31#

[V1270]
Meter=Image
MeterStyle=V270|STPC
LeftMouseUpAction=[#VVS# "DA1" "164,52,99" #@#Style.inc]#MTAJR1##Cout32#

[V1280]
Meter=Image
MeterStyle=V280|STPC
LeftMouseUpAction=[#VVS# "DA1" "219,179,40" #@#Style.inc]#MTAJR1##Cout33#

[V1290]
Meter=Image
MeterStyle=V290|STPC
LeftMouseUpAction=[#VVS# "DA1" "161,197,4" #@#Style.inc]#MTAJR1##Cout34#

[V1300]
Meter=Image
MeterStyle=V300|STPC
LeftMouseUpAction=[#VVS# "DA1" "33,115,70" #@#Style.inc]#MTAJR1##Cout35#

[V1310]
Meter=Image
MeterStyle=V310|STPC
LeftMouseUpAction=[#VVS# "DA1" "47,210,6" #@#Style.inc]#MTAJR1##Cout36#

[V1320]
Meter=Image
MeterStyle=V320|STPC
LeftMouseUpAction=[#VVS# "DA1" "3,208,252" #@#Style.inc]#MTAJR1##Cout37#

[V1330]
Meter=Image
MeterStyle=V330|STPC
SolidColor=52,92,252
LeftMouseUpAction=[#VVS# "DA1" "52,92,252" #@#Style.inc]#MTAJR1##Cout38#

[V1340]
Meter=Image
MeterStyle=V340|STPC
LeftMouseUpAction=[#VVS# "DA1" "57,64,197" #@#Style.inc]#MTAJR1##Cout39#


[Ic3a]
Meter=Shape
MeterStyle=BRG|PG3|CSTI
Y=185
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Settings\ColorSpectrum" "Config.ini"]

[Colo3]
Meter=String
MeterStyle=Style|STTitre|PG3
Text=#T2P9#3: 
Y=180

[CurC3]
Meter=Image
MeterStyle=CT
SolidColor=#FBC#
X=50r
Y=4r

[CColo3]
Meter=String
MeterStyle=Style|PG3
Text=(#OACT#) 
X=35r
Y=182

[E225]
Meter=Image
MeterStyle=C225|STPC
LeftMouseUpAction=[#VVS# "FBC" "255,255,0" #@#Style.inc]#MTAJR1##Coup2#
X=180
Y=210

[E325]
Meter=Image
MeterStyle=C325|STPC
LeftMouseUpAction=[#VVS# "FBC" "255,153,0,255" #@#Style.inc]#MTAJR1##Coup3#

[E425]
Meter=Image
MeterStyle=C425|STPC
LeftMouseUpAction=[#VVS# "FBC" "255,27,10" #@#Style.inc]#MTAJR1##Coup4#

[E525]
Meter=Image
MeterStyle=C525|STPC
LeftMouseUpAction=[#VVS# "FBC" "255,0,255" #@#Style.inc]#MTAJR1##Coup5#

[E623]
Meter=Image
MeterStyle=C623|STPC
LeftMouseUpAction=[#VVS# "FBC" "236,0,140" #@#Style.inc]#MTAJR1##Coup6#

[E720]
Meter=Image
MeterStyle=C720|STPC
LeftMouseUpAction=[#VVS# "FBC" "201,255,92, 255" #@#Style.inc]#MTAJR1##Coup7#

[E818]
Meter=Image
MeterStyle=C818|STPC
LeftMouseUpAction=[#VVS# "FBC" "187,187,176,255" #@#Style.inc]#MTAJR1##Coup8#

[E916]
Meter=Image
MeterStyle=C916|STPC
LeftMouseUpAction=[#VVS# "FBC" "161,0,253" #@#Style.inc]#MTAJR1##Coup9#

[E1014]
Meter=Image
MeterStyle=C1014|STPC
LeftMouseUpAction=[#VVS# "FBC" "140,220,57" #@#Style.inc]#MTAJR1##Coup10#

[E8201]
Meter=Image
MeterStyle=T101|STPC
LeftMouseUpAction=[#VVS# "FBC" "161,0,79" #@#Style.inc]#MTAJR1##Coup11#

[E111]
Meter=Image
MeterStyle=C111|STPC
LeftMouseUpAction=[#VVS# "FBC" "134,108,155" #@#Style.inc]#MTAJR1##Coup12#

[E211]
Meter=Image
MeterStyle=T111|STPC
LeftMouseUpAction=[#VVS# "FBC" "252,252,252" #@#Style.inc]#MTAJR1##Coup13#

[E121]
Meter=Image
MeterStyle=C121|STPC
LeftMouseUpAction=[#VVS# "FBC" "130, 227, 113, 89" #@#Style.inc]#MTAJR1##Coup14#

[E131]
Meter=Image
MeterStyle=C131|STPC
LeftMouseUpAction=[#VVS# "FBC" "128,128,64" #@#Style.inc]#MTAJR1##Coup15#

[E141]
Meter=Image
MeterStyle=C141|STPC
LeftMouseUpAction=[#VVS# "FBC" "128,64,0,255" #@#Style.inc]#MTAJR1##Coup16#

[E159]
Meter=Image
MeterStyle=C159|STPC
LeftMouseUpAction=[#VVS# "FBC" "98,46,105" #@#Style.inc]#MTAJR1##Coup17#

[E166]
Meter=Image
MeterStyle=C166|STPC
LeftMouseUpAction=[#VVS# "FBC" "64,128,128" #@#Style.inc]#MTAJR1##Coup18#

[E176]
Meter=Image
MeterStyle=C176|STPC
LeftMouseUpAction=[#VVS# "FBC" "64,0,128" #@#Style.inc]#MTAJR1##Coup19#

[E184]
Meter=Image
MeterStyle=C184|STPC
LeftMouseUpAction=[#VVS# "FBC" "64,153,224" #@#Style.inc]#MTAJR1##Coup20#

[E1901]
Meter=Image
MeterStyle=C1901|STPC
LeftMouseUpAction=[#VVS# "FBC" "0, 171, 255, 255" #@#Style.inc]#MTAJR1##Coup21#

[E2001]
Meter=Image
MeterStyle=C2001|STPC
LeftMouseUpAction=[#VVS# "FBC" "0,128,192" #@#Style.inc]#MTAJR1##Coup22#

[E2101]
Meter=Image
MeterStyle=C2101|STPC
LeftMouseUpAction=[#VVS# "FBC" "0,128,0" #@#Style.inc]#MTAJR1##Coup23#

[E2200]
Meter=Image
MeterStyle=C2200|STPC
LeftMouseUpAction=[#VVS# "FBC" "0,0,255" #@#Style.inc]#MTAJR1##Coup24#

[E8230]
Meter=Image
MeterStyle=C230|STPC
LeftMouseUpAction=[#VVS# "FBC" "0,0,0" #@#Style.inc]#MTAJR1##Coup25#

[E8235]
Meter=Image
MeterStyle=T230|STPC
LeftMouseUpAction=[#VVS# "FBC" "60,60,60" #@#Style.inc]#MTAJR1##Coup26#

[T3121]
Meter=Image
MeterStyle=T121|STPC
LeftMouseUpAction=[#VVS# "FBC" "225,225,225" #@#Style.inc]#MTAJR1##Coup27#

[V2230]
Meter=Image
MeterStyle=V230|STPC
LeftMouseUpAction=[#VVS# "FBC" "102,131,144" #@#Style.inc]#MTAJR1##Coup28#

[V2240]
Meter=Image
MeterStyle=V240|STPC
LeftMouseUpAction=[#VVS# "FBC" "208,52,56" #@#Style.inc]#MTAJR1##Coup29#

[V2250]
Meter=Image
MeterStyle=V250|STPC
LeftMouseUpAction=[#VVS# "FBC" "253,108,63" #@#Style.inc]#MTAJR1##Coup30#

[V2260]
Meter=Image
MeterStyle=V260|STPC
LeftMouseUpAction=[#VVS# "FBC" "249,78,124" #@#Style.inc]#MTAJR1##Coup31#

[V2270]
Meter=Image
MeterStyle=V270|STPC
LeftMouseUpAction=[#VVS# "FBC" "164,52,99" #@#Style.inc]#MTAJR1##Coup32#

[V2280]
Meter=Image
MeterStyle=V280|STPC
LeftMouseUpAction=[#VVS# "FBC" "219,179,40" #@#Style.inc]#MTAJR1##Coup33#

[V2290]
Meter=Image
MeterStyle=V290|STPC
LeftMouseUpAction=[#VVS# "FBC" "161,197,4" #@#Style.inc]#MTAJR1##Coup34#

[V2300]
Meter=Image
MeterStyle=V300|STPC
LeftMouseUpAction=[#VVS# "FBC" "33,115,70" #@#Style.inc]#MTAJR1##Coup35#

[V2310]
Meter=Image
MeterStyle=V310|STPC
LeftMouseUpAction=[#VVS# "FBC" "47,210,6" #@#Style.inc]#MTAJR1##Coup36#

[V2320]
Meter=Image
MeterStyle=V320|STPC
LeftMouseUpAction=[#VVS# "FBC" "3,208,252" #@#Style.inc]#MTAJR1##Coup37#

[V2330]
Meter=Image
MeterStyle=V330|STPC
SolidColor=52,92,252
LeftMouseUpAction=[#VVS# "FBC" "52,92,252" #@#Style.inc]#MTAJR1##Coup38#

[V2340]
Meter=Image
MeterStyle=V340|STPC
LeftMouseUpAction=[#VVS# "FBC" "57,64,197" #@#Style.inc]#MTAJR1##Coup39#

[Ic4a]
Meter=Shape
MeterStyle=BRG|PG3|CSTI
Y=265
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Settings\ColorSpectrum" "Config.ini"]

[Colo4]
Meter=String
MeterStyle=Style|STTitre|PG3
Text=#T2P9#4: 
Y=260

[CurC4]
Meter=Image
MeterStyle=CT
SolidColor=#FBP#
X=50r
Y=4r

[CColo4]
Meter=String
MeterStyle=Style|PG3
Text=(#OACT#) 
X=35r
Y=262

[F225]
Meter=Image
MeterStyle=C225|STPC
LeftMouseUpAction=[#VVS# "FBP" "255,255,0" #@#Style.inc]#MTAJR1##Couq2#
X=180
Y=290

[F325]
Meter=Image
MeterStyle=C325|STPC
LeftMouseUpAction=[#VVS# "FBP" "255,153,0,255" #@#Style.inc]#MTAJR1##Couq3#

[F425]
Meter=Image
MeterStyle=C425|STPC
LeftMouseUpAction=[#VVS# "FBP" "255,27,10" #@#Style.inc]#MTAJR1##Couq4#

[F525]
Meter=Image
MeterStyle=C525|STPC
LeftMouseUpAction=[#VVS# "FBP" "255,0,255" #@#Style.inc]#MTAJR1##Couq5#

[F623]
Meter=Image
MeterStyle=C623|STPC
LeftMouseUpAction=[#VVS# "FBP" "236,0,140" #@#Style.inc]#MTAJR1##Couq6#

[F720]
Meter=Image
MeterStyle=C720|STPC
LeftMouseUpAction=[#VVS# "FBP" "201,255,92, 255" #@#Style.inc]#MTAJR1##Couq7#

[F818]
Meter=Image
MeterStyle=C818|STPC
LeftMouseUpAction=[#VVS# "FBP" "187,187,176,255" #@#Style.inc]#MTAJR1##Couq8#

[F916]
Meter=Image
MeterStyle=C916|STPC
LeftMouseUpAction=[#VVS# "FBP" "161,0,253" #@#Style.inc]#MTAJR1##Couq9#

[F1014]
Meter=Image
MeterStyle=C1014|STPC
LeftMouseUpAction=[#VVS# "FBP" "140,220,57" #@#Style.inc]#MTAJR1##Couq10#

[F8201]
Meter=Image
MeterStyle=T101|STPC
LeftMouseUpAction=[#VVS# "FBP" "161,0,79" #@#Style.inc]#MTAJR1##Couq11#

[F111]
Meter=Image
MeterStyle=C111|STPC
LeftMouseUpAction=[#VVS# "FBP" "134,108,155" #@#Style.inc]#MTAJR1##Couq12#

[F211]
Meter=Image
MeterStyle=T111|STPC
LeftMouseUpAction=[#VVS# "FBP" "252,252,252" #@#Style.inc]#MTAJR1##Couq13#

[F121]
Meter=Image
MeterStyle=C121|STPC
LeftMouseUpAction=[#VVS# "FBP" "130, 227, 113, 89" #@#Style.inc]#MTAJR1##Couq14#

[F131]
Meter=Image
MeterStyle=C131|STPC
LeftMouseUpAction=[#VVS# "FBP" "128,128,64" #@#Style.inc]#MTAJR1##Couq15#

[F141]
Meter=Image
MeterStyle=C141|STPC
LeftMouseUpAction=[#VVS# "FBP" "128,64,0,255" #@#Style.inc]#MTAJR1##Couq16#

[F159]
Meter=Image
MeterStyle=C159|STPC
LeftMouseUpAction=[#VVS# "FBP" "98,46,105" #@#Style.inc]#MTAJR1##Couq17#

[F166]
Meter=Image
MeterStyle=C166|STPC
LeftMouseUpAction=[#VVS# "FBP" "64,128,128" #@#Style.inc]#MTAJR1##Couq18#

[F176]
Meter=Image
MeterStyle=C176|STPC
LeftMouseUpAction=[#VVS# "FBP" "64,0,128" #@#Style.inc]#MTAJR1##Couq19#

[F184]
Meter=Image
MeterStyle=C184|STPC
LeftMouseUpAction=[#VVS# "FBP" "64,153,224" #@#Style.inc]#MTAJR1##Couq20#

[F1901]
Meter=Image
MeterStyle=C1901|STPC
LeftMouseUpAction=[#VVS# "FBP" "0, 171, 255, 255" #@#Style.inc]#MTAJR1##Couq21#

[F2001]
Meter=Image
MeterStyle=C2001|STPC
LeftMouseUpAction=[#VVS# "FBP" "0,128,192" #@#Style.inc]#MTAJR1##Couq22#

[F2101]
Meter=Image
MeterStyle=C2101|STPC
LeftMouseUpAction=[#VVS# "FBP" "0,128,0" #@#Style.inc]#MTAJR1##Couq23#

[F2200]
Meter=Image
MeterStyle=C2200|STPC
LeftMouseUpAction=[#VVS# "FBP" "0,0,255" #@#Style.inc]#MTAJR1##Couq24#

[F8230]
Meter=Image
MeterStyle=C230|STPC
LeftMouseUpAction=[#VVS# "FBP" "0,0,0" #@#Style.inc]#MTAJR1##Couq25#

[F8235]
Meter=Image
MeterStyle=T230|STPC
LeftMouseUpAction=[#VVS# "FBP" "60,60,60" #@#Style.inc]#MTAJR1##Couq26#

[T4521]
Meter=Image
MeterStyle=T121|STPC
LeftMouseUpAction=[#VVS# "FBP" "225,225,225" #@#Style.inc]#MTAJR1##Couq27#

[V6230]
Meter=Image
MeterStyle=V230|STPC
LeftMouseUpAction=[#VVS# "FBP" "102,131,144" #@#Style.inc]#MTAJR1##Couq28#

[V6240]
Meter=Image
MeterStyle=V240|STPC
LeftMouseUpAction=[#VVS# "FBP" "208,52,56" #@#Style.inc]#MTAJR1##Couq29#

[V6250]
Meter=Image
MeterStyle=V250|STPC
LeftMouseUpAction=[#VVS# "FBP" "253,108,63" #@#Style.inc]#MTAJR1##Couq30#

[V6260]
Meter=Image
MeterStyle=V260|STPC
LeftMouseUpAction=[#VVS# "FBP" "249,78,124" #@#Style.inc]#MTAJR1##Couq31#

[V6270]
Meter=Image
MeterStyle=V270|STPC
LeftMouseUpAction=[#VVS# "FBP" "164,52,99" #@#Style.inc]#MTAJR1##Couq32#

[V6280]
Meter=Image
MeterStyle=V280|STPC
LeftMouseUpAction=[#VVS# "FBP" "219,179,40" #@#Style.inc]#MTAJR1##Couq33#

[V6290]
Meter=Image
MeterStyle=V290|STPC
LeftMouseUpAction=[#VVS# "FBP" "161,197,4" #@#Style.inc]#MTAJR1##Couq34#

[V6300]
Meter=Image
MeterStyle=V300|STPC
LeftMouseUpAction=[#VVS# "FBP" "33,115,70" #@#Style.inc]#MTAJR1##Couq35#

[V6310]
Meter=Image
MeterStyle=V310|STPC
LeftMouseUpAction=[#VVS# "FBP" "47,210,6" #@#Style.inc]#MTAJR1##Couq36#

[V6320]
Meter=Image
MeterStyle=V320|STPC
LeftMouseUpAction=[#VVS# "FBP" "3,208,252" #@#Style.inc]#MTAJR1##Couq37#

[V6330]
Meter=Image
MeterStyle=V330|STPC
SolidColor=52,92,252
LeftMouseUpAction=[#VVS# "FBP" "52,92,252" #@#Style.inc]#MTAJR1##Couq38#

[V6340]
Meter=Image
MeterStyle=V340|STPC
LeftMouseUpAction=[#VVS# "FBP" "57,64,197" #@#Style.inc]#MTAJR1##Couq39#