
[Recy]
Meter=String
MeterStyle=Style|STTitre|PG4
Text=#RecBin#
Y=150
Tooltiptitle=#PTRCP#
Tooltiptext=#DSTM#

[Currrecy]
Meter=String
MeterStyle=Style|PG4
X=260
Y=2r
Text=#cort# (#OACT#)

[STRec]
X=32r
Y=152
Group=G4
Hidden=1
UpdateDivider=-1

[Rc1e]
Meter=String
MeterStyle=Style|STRec
X=400
Text=150
LeftMouseUpAction=[#VVS# "CorT" "150" "#@#Style.inc"][!Refresh "#ROOTCONFIG#\HDD\Recycle"][!SetOption Currrecy Text "150 (#OACT#)"][!UpdateMeter Currrecy][!Redraw]

[Rc2e]
Meter=String
MeterStyle=Style|STRec
Text=250
LeftMouseUpAction=[#VVS# "CorT" "250" "#@#Style.inc"][!Refresh "#ROOTCONFIG#\HDD\Recycle"][!SetOption Currrecy Text "250 (#OACT#)"][!UpdateMeter Currrecy][!Redraw]

[Rc3e]
Meter=String
MeterStyle=Style|STRec
Text=350
LeftMouseUpAction=[#VVS# "CorT" "350" "#@#Style.inc"][!Refresh "#ROOTCONFIG#\HDD\Recycle"][!SetOption Currrecy Text "350 (#OACT#)"][!UpdateMeter Currrecy][!Redraw]

[Rc14e]
Meter=String
MeterStyle=Style|STRec
Text=450
LeftMouseUpAction=[#VVS# "CorT" "450" "#@#Style.inc"][!Refresh "#ROOTCONFIG#\HDD\Recycle"][!SetOption Currrecy Text "450 (#OACT#)"][!UpdateMeter Currrecy][!Redraw]

[Rc15e]
Meter=String
MeterStyle=Style|STRec
Text=550
LeftMouseUpAction=[#VVS# "CorT" "550" "#@#Style.inc"][!Refresh "#ROOTCONFIG#\HDD\Recycle"][!SetOption Currrecy Text "550 (#OACT#)"][!UpdateMeter Currrecy][!Redraw]

[Rc16e]
Meter=String
MeterStyle=Style|STRec
Text=650
LeftMouseUpAction=[#VVS# "CorT" "650" "#@#Style.inc"][!Refresh "#ROOTCONFIG#\HDD\Recycle"][!SetOption Currrecy Text "650 (#OACT#)"][!UpdateMeter Currrecy][!Redraw]

[Rc17e]
Meter=String
MeterStyle=Style|STRec
Text=750
LeftMouseUpAction=[#VVS# "CorT" "750" "#@#Style.inc"][!Refresh "#ROOTCONFIG#\HDD\Recycle"][!SetOption Currrecy Text "750 (#OACT#)"][!UpdateMeter Currrecy][!Redraw]

[Rc18e]
Meter=String
MeterStyle=Style|STRec
Text=850
LeftMouseUpAction=[#VVS# "CorT" "850" "#@#Style.inc"][!Refresh "#ROOTCONFIG#\HDD\Recycle"][!SetOption Currrecy Text "850 (#OACT#)"][!UpdateMeter Currrecy][!Redraw]

[Rc19e]
Meter=String
MeterStyle=Style|STRec
Text=950
LeftMouseUpAction=[#VVS# "CorT" "950" "#@#Style.inc"][!Refresh "#ROOTCONFIG#\HDD\Recycle"][!SetOption Currrecy Text "950 (#OACT#)"][!UpdateMeter Currrecy][!Redraw]